---
title: "Seattle Food Map"
author: "Matthew Richards"
date: "January 22, 2017"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Good Food in Seattle, WA (01/22/2017)
```{r}
suppressWarnings(library(leaflet))

# Create the data frame
seattle_loc <- data.frame(
  lat = c(47.60972,47.5994409,47.6816841,47.6611935,
          47.67538,47.6577795,47.6225807,47.6861061),
  lng = c(-122.344387,-122.3312286,-122.3786947,-122.3422866,
          -122.327614,-122.3197193,-122.2994758,-122.3403572),
  col = c("blue", "red", "red","purple",
          "green","green","purple","blue"),
  stringsAsFactors = FALSE
)

seattle_sites <- c(
  "<a href='http://pikeplacemarket.org/'>Pike Place Market</a>",
  "<a href='http://www.salumicuredmeats.com/'>Salumi</a>",
  "<a href='http://unbienseattle.com/'>Un Bien</a>",
  "<a href='http://tilthrestaurant.com/home/'>Tilth</a>",
  "<a href='http://www.butcherbakerseattle.com/'>The Butcher & The Baker</a>",
  "<a href='http://www.portagebaycafe.com/'>Portage Bay Cafe</a>",
  "<a href='http://www.harvestvine.com/'>The Harvest Vine</a>",
  "<a href='http://www.dukeschowderhouse.com/locations/green-lake/'>Duke's Chowder House</a>"
)

suppressMessages(seattle_loc %>%
  leaflet() %>%
  addTiles() %>%
  addCircleMarkers(popup = seattle_sites,
                   color=seattle_loc$col) %>%
  addLegend(labels = c("Seafood", "Sandwiches","Brunch","Upscale"),
            colors = c("blue", "red","green","purple"))
)
```
