---
title: "Seattle Food Map Presentation"
author: "Matthew Richards"
date: "February 5, 2017"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## An Overview

Seattle, WA has a vibrant food scene, with many different types of cuisine around the city. As a food-loving individual, I am often asked about my recommendations around the city, but I can't always think of all the places I enjoy. It would be very useful to have a dynamic tool to help recommend my favorite places to others.

This Shiny app serves as a useful aid; it contains 20 of my favorite eateries from around Seattle, categorized by food type and mapped out using the Leaflet package in R.

## What it Offers

My app is essentially an organized, interactive map of 20 Seattle restaurants. The user is presented with: 

* Check boxes that allow them to filter what type of restaurants they are interested in
* An "Update Map" button that is used to apply restaurant filtering
* A map of restaurants colored by type and coded by a legend
* Clickable markers that display the restaurant's name as popup text and also serve as hyperlinks to the restaurant's home webpage. 

For a more in-depth look at the back end, let's take a quick look at what the user interface and server do in my app. 

## The User Interface

My user interface is fairly simple and does the following operations:

1. In the side panel, it presents the user with a set of checkboxes to filter different restaurant types

2. Below the checkboxes, it contains a submitButton element to update the output based on the user's checkbox input. 

3. In the main panel, it contains a leaflet map output that depends on the user input. 

4. Below the map, it presents a short set of instructions for usage. 

## The Server

My server function does the following:

1. Creates the data frame of all 20 locations, including:
    + Longitude and Latitude
    + Marker Color
    + Hyperlink to the website

2. Creates a legend linking each color to a restaurant type

3. Defines a reactive expression to filter locations based on user input. This is  my server's main calculation. 

4. Renders a Leaflet map using the filtered data frame and filtered legend


